### ISSUE TITLE
Calling hdf5 Dataset.read_acquisition() results in segmentation fault

### ISSUE THREAD

**Issue by ohinds** [ismrmrd/ismrmrd-python#14] opened 2016-11-28 21:17 UTC
When loading any acquistion from an HD5 ISMRMRD dataset, python crashes with a segmentation fault in numpy. The acquisitions load fine in a program written using the C++ ismrmrd library. Multiple raw data files from different pulse sequences were tested with the same result.

Python code:
```python
#!/usr/bin/env python

import ismrmrd
import sys
import xmltodict

def main(argv):
    rd = ismrmrd.Dataset(argv[1])
    header_xml = rd.read_xml_header()
    header = xmltodict.parse(header_xml)
    print "Dataset contains %d acquisitions" % rd.number_of_acquisitions()

    acq = rd.read_acquisition(0) ## seg fault here
    print "acquisition 0 has %d samples" % acquisition.number_of_samples

if __name__ == "__main__":
    sys.exit(main(sys.argv))
```

Python output:
```
Dataset contains 1089 acquisitions

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff61144a8 in PyArray_Item_XDECREF (data=0x121c138 "\377\177",
descr=0x7fffef193ed0)
    at numpy/core/src/multiarray/refcount.c:71
71      numpy/core/src/multiarray/refcount.c: No such file or
directory.
(gdb) bt
#0  0x00007ffff61144a8 in PyArray_Item_XDECREF (data=0x121c138
"\377\177", descr=0x7fffef193ed0)
    at numpy/core/src/multiarray/refcount.c:71
#1  0x00007ffff6114467 in PyArray_Item_XDECREF (data=0x121bfe0 "\001",
descr=0x7fffef193f90)
    at numpy/core/src/multiarray/refcount.c:87
#2  0x00007ffff6114976 in PyArray_XDECREF (mp=mp@entry=0x7fffef197ee0)
at numpy/core/src/multiarray/refcount.c:173
#3  0x00007ffff60435b4 in array_dealloc (self=0x7fffef197ee0) at
numpy/core/src/multiarray/arrayobject.c:418
#4  0x00007ffff6118373 in void_dealloc (v=0x7fffef1fd7d8) at
numpy/core/src/multiarray/scalartypes.c.src:2501
#5  0x00007ffff604357b in array_dealloc (self=0x7fffef1979e0) at
numpy/core/src/multiarray/arrayobject.c:411
#6  0x00007ffff604357b in array_dealloc (self=0x7fffef197f30) at
numpy/core/src/multiarray/arrayobject.c:411
#7  0x00007ffff6118373 in void_dealloc (v=0x7fffef1fd7a0) at
numpy/core/src/multiarray/scalartypes.c.src:2501
#8  0x00000000004cdb00 in PyEval_EvalFrameEx ()
#9  0x00000000004cd4e2 in PyEval_EvalFrameEx ()
#10 0x00000000004cd4e2 in PyEval_EvalFrameEx ()
#11 0x00000000004cb6b1 in PyEval_EvalCodeEx ()
#12 0x000000000050481f in ?? ()
#13 0x00000000004fc182 in PyRun_FileExFlags ()
#14 0x00000000004fb247 in PyRun_SimpleFileExFlags ()
#15 0x000000000049aa6e in Py_Main ()
#16 0x00007ffff7811a40 in __libc_start_main (main=0x49a500 <main>,
argc=3, argv=0x7fffffffd518, init=<optimized out>,
    fini=<optimized out>, rtld_fini=<optimized out>,
stack_end=0x7fffffffd508) at libc-start.c:289
#17 0x000000000049a429 in _start ()
```

pip freeze:
```
Pil-Lite==0.0.6
PyXB==1.2.5
Pygments==2.1.3
argparse==1.2.1
backports.shutil-get-terminal-size==1.0.0
decorator==4.0.10
enum34==1.1.6
h5py==2.6.0
ipdb==0.10.1
ipython==5.1.0
ipython-genutils==0.1.0
ismrmrd==1.3.3
mpmath==0.19
nibabel==2.1.0
nipy==0.5.0.dev0
numpy==1.11.2
pathlib2==2.1.0
pexpect==4.2.1
pickleshare==0.7.4
prompt-toolkit==1.0.9
ptyprocess==0.5.1
pydicom==0.9.9
scipy==0.18.1
simplegeneric==0.8.1
six==1.10.0
sympy==1.0
traitlets==4.3.1
wcwidth==0.1.7
wsgiref==0.1.2
xmltodict==0.10.2
```

Operational C++ code:
```c++
#include <iostream>
#include <string>

#include "ismrmrd/ismrmrd.h"
#include "ismrmrd/dataset.h"

using std::cout;
using std::endl;
using std::string;

int main(int argc, char** argv) {

    string filename(argv[1]);

    ISMRMRD::Dataset dataset(filename.c_str(), "dataset");

    cout << "Dataset contains " << dataset.getNumberOfAcquisitions()
         << " acquisitions" << endl;

    ISMRMRD::Acquisition acq;
    dataset.readAcquisition(0, acq);

    cout << "acquisition 0 has " << acq.number_of_samples() << " samples"
         << endl;

    return 0;
}
```

**Comment by hansenms** [comment] 2016-11-29 18:07
Thank you for reporting this. I can confirm that this is an issue. It seems to be related to h5py 2.6.0. I have a machine with 2.4.0 and there it seems to be working. 

I will do some looking into this.

**Comment by ohinds** [comment] 2016-11-29 23:48
Great, thanks. It also seems to work with h5py 2.5.0.

**Comment by hansenms** [comment] 2016-11-30 01:12
I can confirm that too. Doing:

    pip install 'h5py==2.5.0' --force-reinstall

Fixes the problem. There could be a bug in 2.6.0. More investigation is needed. It would be great to have a small (ISMRMRD independent) example that reproduces this problem.

**Comment by hansenms** [comment] 2016-11-30 01:51
Well, I did some more searching (bisecting the h5py code) and a bug regarding aligned compound data types (which is what ISMRMRD) uses was introduced in this commit:

https://github.com/h5py/h5py/commit/0d6b88def48a53241511ef287f722105b6142ce1

And it stayed in through the release of version 2.6.0, but was subsequently fixed in this commit: 

https://github.com/h5py/h5py/commit/05dbd2d59df765b4e365393fbd82f1d0f38b5d83 

Since then it has been working, so this issue is labeled "wontfix", but maybe it should be can't fix. Your (and my) options are to stick with h5py 2.5.0:

    pip install 'h5py==2.5.0' --force-reinstall

until 2.7.0 is release or alternatively go bleeding edge and install the latest version from the git repo:

    pip uninstall h5py
    git clone https://github.com/h5py/h5py.git
    cd h5py
    python setup.py install

And hope that there are no other bugs. 

Thanks for bringing this to our attention. I will keep the issue open until there is a new version and we can add that to the discussion and close the issue. 

Does that help you out enough for now?

**Comment by hansenms** [comment] 2016-11-30 01:58
See also:

https://github.com/h5py/h5py/issues/742

**Comment by ohinds** [comment] 2016-11-30 04:39
Yup, I'm all set, thanks!

**Comment by tacaswell** [comment] 2016-12-27 22:01
Just a quick note that there will be a h5py2.7 in the next month or so.

**Comment by hansenms** [comment] 2016-12-27 22:14
@tacaswell Thanks. We will keep an eye out for it and do some testing once it is out.

**Closed** 2022-02-25 05:31 UTC
Labels: wontfix
